version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:8000 darwix_ai_project.wsgi:application
    
  # Uncomment if you want to use a database like PostgreSQL
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_DB=${DB_NAME}

# Uncomment if using PostgreSQL
# volumes:
#   postgres_data: